### ISSUE TITLE
tags without quotation marks

### ISSUE THREAD

**Issue by Robert-Steiner** [Empty2k12/influxdb-rust#60]
Hey, first of all, thank you very much for the great work.

I have a question about the InfluxDbWriteable derive. I updated the influxdb crate to 0.1.0 a few days ago. 
I'm now using the InfluxDbWriteable derive instead of creating a write query. Everything works as it should, but I've noticed that the string field that I've marked as `#tag` is saved with quotation marks. (instead of saving `abc`, my influxdb instance saves the value `"abc"`.
Is the a way to store the tag field without quotation marks?

**Comment by Empty2k12** [comment]
Hello Robert. Thanks for opening this issue!

This behavior was likely introduced in https://github.com/Empty2k12/influxdb-rust/commit/90f5f95529a7f97dac5937d47433f7d132485737 (Pull Request #55) with some further improvements in https://github.com/Empty2k12/influxdb-rust/commit/cb7f08cd811e17271bb8324c886b8bff8d444f49 where the escapting code was adapted to match the expected behavior from InfluxDB docs. 

Could you post a code snippet that is causing the wrong behavior?

**Comment by Robert-Steiner** [comment]
Hey, thanks for your response. I created a small example https://github.com/Robert-Steiner/influxdb-tags
